# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- synapse

pool:
  vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'


jobs:
  - job: BuildJob
    displayName: Build Job
    steps:

    # - task: DotNetCoreCLI@2
    #   displayName: dotnet build
    #   inputs:
    #     command: 'build'
    #     projects: '$(Build.SourcesDirectory)/101-synapse-poc/*'
        
    # - task: DotNetCoreCLI@2
    #   displayName: dotnet publish
    #   inputs:
    #     command: 'publish'
    #     publishWebProjects: true
    #     arguments: '--output $(Build.ArtifactStagingDirectory)'
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/101-synapse-poc/*'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactsStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: publish artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'