# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- synapse

pool:
  vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'


jobs:
  - job: BuildJob
    displayName: Build Job
    steps:

    # - task: DotNetCoreCLI@2
    #   displayName: dotnet build
    #   inputs:
    #     command: 'build'
    #     projects: '$(Build.SourcesDirectory)/101-synapse-poc/*'
        
    # - task: DotNetCoreCLI@2
    #   displayName: dotnet publish
    #   inputs:
    #     command: 'publish'
    #     publishWebProjects: true
    #     arguments: '--output $(Build.ArtifactStagingDirectory)'
    
    - powershell: |
                cd $(Build.SourcesDirectory)
                ls
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/101-synapse-poc/*'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactsStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: publish artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

  - deployment: 
    displayName: ARM Template
    environment: develop
    dependsOn: BuildJob
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.ArtifactsDirectory)'
            
            - powershell: |
                cd $(System.ArtifactsDirectory)
                ls

            - task: AzureResourceManagerTemplateDeployment@3
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: 'MVP Sponsorship'
                subscriptionId: '337ba254-3aa0-4551-ba8e-89debefaa373'
                action: 'Create Or Update Resource Group'
                resourceGroupName: 'RG-Synapse'
                location: '$(System.ArtifactsDirectory)/'
                templateLocation: 'Linked artifact'
                deploymentMode: 'Incremental'